baseURL = "https://pahnev.cf/"
languageCode = "en-us"
title = "Kirill Pahnev"
theme = "mini"

[taxonomies]
	tag = "tags"

[params]
	author = "Kirill Pahnev"
	description = "The personal site of Kirill Pahnev"
	bio = "iOS Developer"
	copyright = "© Copyright 2022 Kirill Pahnev"
	avatarLink = "https://pahnev.cf"

	enableToc = false
	enableSummary = false

	# 404 page
	title404 = "Oops"
	subtitle404 = "We got lost..."

	customCSS = ["css/custom.css"]
	enableRSS = true

[social]
	twitter = "https://www.twitter.com/kirillpahnev"
	github = "https://www.github.com/pahnev"
	stackoverflow = "https://stackoverflow.com/users/2143387/pahnev"
    linkedin = "https://www.linkedin.com/in/kirillpahnev/"
